#!/bin/bash

#Remove the most rescent container that ran
docker rm $(docker ps -aq --latest)

#Pull the latest tagged image from Docker Hub
docker pull jackewing/cicd-project:latest

#Create a container off that image
docker run -d --restart=always --name cd_cdontainer jackewing/cicd-project:latest

#       Variables       #

#Script
SCRIPT_NAME=$(basename "$0")
SOURCE_DIR=$(dirname "$readlink -f "$0")")
SOURCE_PATH="$SOURCE_DIR/$SCRIPT_NAME"

#Repo Path
REPO_PATH="WSU-kduncan/cicdf25-JackEwing42"

#Destination
DEPLOY_DIR="deployment"
DESTINATION_PATH="$REPO_PATH/$DEPLOY_DIR/$SCRIPT_NAME"

#Commit message
COMMIT_MSG="Add $SCRIPT_NAME to the deployment folder"

#       Actions       #

#Start message
echo "Starting deployment Script copy and push process..."

#Step 1. Enter the local repo directory
cd "$REPO_PATH" || {echo "error: Could not change directory to $REPO_PATH"; exit 1; }

#Step 2. Create deployment folder (if it does not exist)
mkdir -p "$DEPLOY_DIR"

#Step 3. Copy Script to Repo
cp "$SOURCE_PATH" "$DESTINATION_PATH"
if [ $? -eq 0 ]; then
        echo "Successfully copied script to $DESTINATION_PATH"
else
        echo "Error: Failed to copy script"
        exit 1
fi

#Step 4. Stage for a Commit
git add "$DEPLOY_DIR/$SCRIPT_NAME"
echo "Staged changes..."

#Step 5. Commit changes
git commit -m "$Commit_MSG
if [ $? -eq 0 ]; then
        echo "Commited changes locally."
else
        echo "No new changes to commit. Exiting Git process."
        exit 0
fi

Step 6. Push changes
if [ $? -eq 0 ]; then
        echo "Succesfully pushed changes to GitHub."
else
        echo "Error: Failed to push changes to GitHub. Check your credentials/permissions."
        exit 1
fi

#Final check
echo "Process complete"
