#!/bin/bash

#Abort any ongoing rebase
if git rebase --abort 2>/dev/null; then
    echo "Aborted ongoing rebase."
fi

#Remove the most rescent container that ran
LATEST=$(docker ps -aq --latest)
if [ -n "$LATEST" ]; then
        docker rm -f "$LATEST"
else
        echo "No existing container to remove."
fi

#Pull the latest tagged image from Docker Hub
docker pull jackewing/cicd-project:latest

#Create a container off that image
docker run -d --restart=always --name cd_container jackewing/cicd-project:latest

#       Variables       #

#Script
SCRIPT_NAME=$(basename "$0")
SOURCE_DIR=$(dirname "$(readlink -f "$0")")
SOURCE_PATH="$SOURCE_DIR/$SCRIPT_NAME"

#Repo Path
REPO_PATH="/home/ec2-user/cicdf25-JackEwing42"

#Destination
DEPLOY_DIR="deployment"
DESTINATION_PATH="$REPO_PATH/$DEPLOY_DIR/$SCRIPT_NAME"

#Commit message
COMMIT_MSG="Add $SCRIPT_NAME to the deployment folder"

#       Actions       #

#Start message
echo "Starting deployment Script copy and push process..."

#Step 1. Enter the local repo directory
cd "$REPO_PATH" || { echo "error: Could not change directory to $REPO_PATH"; exit 1; }

#Step 2. Create deployment folder (if it does not exist)
mkdir -p "$DEPLOY_DIR"

#Step 3. Copy Script to Repo
cp "$SOURCE_PATH" "$DESTINATION_PATH"
if [ $? -eq 0 ]; then
        echo "Successfully copied script to $DESTINATION_PATH"
else
        echo "Error: Failed to copy script"
        exit 1
fi

#Step 4. Fetch Repo Branch
git fetch origin
git reset --hard origin/main
echo "Branch successfully fetched..."

#Step 5. Stage for a Commit
git add "$DEPLOY_DIR/$SCRIPT_NAME"
echo "Staged changes..."

#Step 6. Commit changes
if git commit -m "$COMMIT_MSG";  then
        echo "Commited changes locally."
else
        echo "No new changes to commit. Exiting Git process."
        exit 0
fi

#Step 7. Push changes
if git push origin main; then
        echo "Succesfully pushed changes to GitHub."
else
        echo "Error: Failed to push changes to GitHub. Check your credentials/permissions."
        exit 1
fi

#Final check
echo "Process complete"
